source 'http://rubygems.org'


gem 'cucumber',                   '~> 2.1.0'
gem 'rspec-expectations',         '~> 3.3.0'
gem 'factory_girl',               '~> 4.5.0'
gem 'require_all',                '~> 1.3.3'
gem 'pry',                        '~> 0.10.3'
gem 'selenium-webdriver',         '~>2.53.4'
gem 'capybara',                   '~> 2.5.0'
gem 'poltergeist',                '~> 1.7.0'
gem 'parallel_tests',             '~> 1.9.0'
#gem 'relish',                    '~> 0.7.1'
gem 'site_prism',                 '~> 2.8'
#gem 'pretty_face',               '~> 0.10.3'
gem 'capybara-screenshot',        '~> 1.0.11'
gem 'cuke_sniffer',               '~> 0.0.8'
gem 'rake',                       '~> 10.4.2'
gem 'hirb',                       '~> 0.7.3'
#gem 'google-api-client', '~> 0.8.6'
gem 'rubysl-securerandom', '~> 2.0'
gem 'activesupport', '~> 4.2'
gem 'colorize', '~> 0.8.1'
